name: Continuous deployment
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REPOSITORY: ${{ secrets.CONTAINER_REPOSITORY }}
  IMAGE_NAME: todo-app
  IMAGE_TAG: latest

jobs:
  build_container_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build image
        run: docker build -t $REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
      - name: Save image
        run: docker save $REPOSITORY/$IMAGE_NAME:$IMAGE_TAG -o $IMAGE_NAME-$GITHUB_SHA.tar
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-${{ github.sha }}
          path: ${{ env.IMAGE_NAME }}-${{ github.sha }}.tar
          if-no-files-found: error
  deploy_container_image:
    name: Deploy image
    runs-on: ubuntu-latest
    needs: build_container_image
    steps:
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-${{ github.sha }}
      - name: Load Docker image
        run: docker load -i $IMAGE_NAME-$GITHUB_SHA.tar
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REPOSITORY }}
          username: ${{ secrets.CONTAINER_REPOSITORY_USER }}
          password: ${{ secrets.CONTAINER_REPOSITORY_TOKEN }}
      - name: Push image
        run: docker push $REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
